//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirajayaRMS.Web {
    
    
    public partial class NotAuthorized {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WirajayaRMS.Web.Site Master {
            get {
                return ((WirajayaRMS.Web.Site)(base.Master));
            }
        }
    }
}
